import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import { Button, Card, CardContent, CardMedia, Grid } from "@mui/material";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mombasa Album</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container spacing={1}>
          <Grid item xs={12} md={8} lg={8}>
            <Card>
              <CardMedia
                component="img"
                height="300px"
                image="https://fastly.picsum.photos/id/20/3670/2462.jpg?hmac=CmQ0ln-k5ZqkdtLvVO23LjVAEabZQx2wOaT4pyeG10I"
              />
              <CardContent>
                <h5>This is side A</h5>
                <Button variant="outlined" color="primary"><Link href="/about">About Us</Link></Button>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12} md={4} lg={4}>
            <Card>
              <CardMedia
                component="img"
                height="300px"
                image="https://fastly.picsum.photos/id/28/4928/3264.jpg?hmac=GnYF-RnBUg44PFfU5pcw_Qs0ReOyStdnZ8MtQWJqTfA"
              />
              <CardContent>
                <h5>This is side B</h5>
                <Button variant="outlined">
                  <Link href="/photos">View Photos</Link>
                </Button>
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      </main>
    </>
  );
}
